import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router'
import React, { useEffect } from 'react'
import { IoBookOutline } from 'react-icons/io5'
import RecipeItem from '../../components/RecipeItem'
import { useStateContext } from '../../context/ContextProvider'
import Layout from '../../layout/Layout'
import { FlexColumnCenteredDiv, FlexRowDiv } from '../../styles/styles'
import { AlertText, H1, H2 } from '../../styles/texts'
import { Grid } from '../recipes/styles'

const Profile = () => {
  const router = useRouter();
  const ctx = useStateContext();

  useEffect(() => {
    if (!ctx?.userData) {
      router.push('login');
    }
  }, [])

  return (
    <>
      <Head>
        <title>Luv&amp;Kitchen - Profile</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <FlexColumnCenteredDiv>
          <Image 
            src={require('../../public/avatars/'+ctx?.userData?.avatar_img)}
            alt=""
            width={200}
            height={200}
            style={{ borderRadius: '50%', objectFit: 'cover' }}
          />
          <H1 style={{ marginBottom: '50px', marginTop: '25px' }}>
            { ctx?.userData?.name }
          </H1>
          <H2 marginSize='none'>
            <FlexRowDiv>
              <IoBookOutline style={{ marginRight: '8px' }} />
              My Book of Recipes
            </FlexRowDiv>
          </H2>
          
          {ctx?.userData?.favorites && ctx?.userData?.favorites.length > 0 ?
            <Grid>
              {
                ctx.userData.favorites
                  .map((item) => 
                    (
                      ''
                    )
                  )
              }
            </Grid>
          :
            <AlertText semibold style={{ textAlign: 'center', marginTop: '30px' }}>
              You have no recipes in your Book
            </AlertText>
          }
          
        </FlexColumnCenteredDiv>


      </Layout>
    </>
  )
}

export default Profile