import Link from 'next/link'
import React, { useState } from 'react'
import styled from 'styled-components'
import InputContainer from '../../components/InputContainer'
import Logo from '../../components/Logo'
import { ButtonPrimary } from '../../styles/buttons'
import { FlexRowDiv } from '../../styles/styles'
import { AlertText, Callout, H1, P } from '../../styles/texts'
import { colors } from '../../styles/theme'
import LoginBgImage from '../../public/images/login-bg.jpg'
import { Input, PasswordInput } from '../../styles/inputs'
import Head from 'next/head'
import { SubmitHandler, useForm } from 'react-hook-form'
import { useMutation } from 'react-query'
import login from '../../services/auth/login'
import { RiErrorWarningLine } from 'react-icons/ri'
import { useRouter } from 'next/router'
import getUserInfo from '../../services/auth/getUserInfo'
import { useStateContext } from '../../context/ContextProvider'
import { LoginData } from '../../@types/AuthTypes'

const Login = () => {
  const router = useRouter();
  const redirectToPage = router.query;
  const ctx = useStateContext();
  const { register, handleSubmit, watch, formState: { errors } } = useForm<LoginData>();
  const [ requestError, setRequestError ] = useState('');
  const { mutate, isLoading } = useMutation(login, {
    onSuccess: async (response) => {
      if (response?.status === 200) {
        const userInfo = await getUserInfo(response.data.token)
          .then(res => {
              return res?.data.data
          })
          .catch(err => console.log(err))

        ctx?.saveUserSession({ 
          token: response.data.token, 
          name: userInfo.name, 
          avatar_img: userInfo.avatar_img, 
          favorites: userInfo.favorites 
        })

        if (redirectToPage?.next) {
          router.push(redirectToPage.next);
        } else {
          router.push('/');
        }
      }
    },
    onError: ({response}) => {
      setRequestError(response.data.message)
    }
  });

  const handleLogin : SubmitHandler<LoginData> = (data) => {
    mutate(data);
  }

  return (
    <>
      <Head>
        <title>Luv&amp;Kitchen - Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <FlexRowDiv style={{ height: '100vh', backgroundColor: colors.light, overflowY: 'auto' }}>
          <LeftContentDiv>
            <div style={{ margin: '20px 0 0 30px' }}>
              <Logo />
            </div>
          </LeftContentDiv>
          <div style={{ padding: '0 200px', width: '40%' }}>
            <LoginForm onSubmit={handleSubmit(handleLogin)} method="post">
                <H1>
                  Login
                </H1>

                <div style={{ width: '100%' }}>
                  <InputContainer
                    label={'Username'}
                  >
                    <Input 
                      type="text"
                      placeholder="CordonBleuChef"
                      register={register}
                      name="email"
                      validationSchema={{ required: true }}
                    />
                    <AlertText>
                      {errors?.email && errors.email.message}
                    </AlertText>
                  </InputContainer>

                  <InputContainer
                    label={'Password'}
                  >
                    <PasswordInput
                      type="password"
                      placeholder='Your password'
                      register={register}
                      name="password"
                      validationSchema={{ required: true }}
                    />
                    <AlertText>
                      {errors?.password && errors.password.message}
                    </AlertText>
                  </InputContainer>

                  {requestError &&
                    <AlertText>
                      <FlexRowDiv>
                        <RiErrorWarningLine style={{ marginRight: '5px' }} />
                        {requestError}
                      </FlexRowDiv>
                    </AlertText>
                  }

                  <Link href="/">
                    <P>
                      Esqueceu sua senha?
                    </P>
                  </Link>
                </div>

                <div style={{textAlign: 'center', width: '100%'}}>
                  <ButtonPrimary style={{ width: '100%' }} type="submit">
                    {isLoading ? 
                      <FlexRowDiv style={{ textAlign: 'center', justifyContent: 'center' }}>
                        <span className='loader' style={{ marginRight: '8px' }}></span> 
                        Logging in.. 
                      </FlexRowDiv>
                     : 
                      'Log in'
                    }
                  </ButtonPrimary>

                  <P style={{ marginTop: '30px', marginBottom: '4px' }}>
                    Does not have an account yet? 
                  </P>
                  <Link href="/register">
                    <AlertText style={{ fontWeight: '500' }}>
                      Register Now
                    </AlertText>
                  </Link>
                </div>

            </LoginForm>
          </div>
      </FlexRowDiv>
    </>
  )
}

const LeftContentDiv = styled.div`
  background-image: url(${LoginBgImage.src});
  background-repeat: no-repeat;
  background-size: cover;
  background-color: #191919;
  background-position-x: 20%;
  height: 100%;
  max-width: 50%;
  width: 100%;
  @media screen and (max-width: 768px) {
    display: none
  }
`

export const LoginForm = styled.form`
  width: 100%;
  height: 100%;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  row-gap: 30px;
`

export default Login