import Head from 'next/head'
import Image from 'next/image'
import Layout from '../layout/Layout'
import { Container } from '../styles/layout'
import { P, H1, H2, H3, H4 } from '../styles/texts'

import Globe from '../../public/images/globe.png';
import Foods from '../../public/images/foods.png';
import FoodHeart from '../../public/images/food-heart.png';
import Cooker from '../../public/images/cooker.png';

import styled from 'styled-components'
import { Button } from '../styles/buttons'


export default function Home() {
  return (
    <>
      <Head>
        <title>Luv&amp;Kitchen</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Main>
          <Container>

            <Header>
              <div>
                <H1>
                  lorem ipsum
                </H1>
                <P>
                  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eveniet ullam qui repellat ratione, laborum blanditiis quia sint sequi quasi quo facere, soluta voluptas ab facilis odio alias architecto nesciunt. Odio?
                </P>
                <Button variant={'secondary'}>
                  View Recipes
                </Button>
              </div>
            </Header>

            <GlobeSection>
              <H2 marginSize='xxl'>
                Experiment food from all over the world
              </H2>
              <Image 
                src={Globe} 
                alt=""
                width={400}
              />
            </GlobeSection>

            <FoodsSection>
              <H3 marginSize={'xxl'}>
                Discover How to Cook a Variety of Recipes.
              </H3>
              <Image 
                src={Foods} 
                alt=""
                width={600}
              />
            </FoodsSection>

            <FavoriteSection>
              <H4 style={{ marginRight: '80px' }}>
                Favorite your most tasteful recipes
              </H4>
              <Image 
                src={FoodHeart} 
                alt=""
                width={400}
              />
            </FavoriteSection>

            <CookerSection>
              <Image 
                src={Cooker} 
                alt=""
                width={400}
              />
            </CookerSection>
          </Container>
        </Main>
      </Layout>
    </>
  )
}

const Main = styled.main`
  margin: 0 auto;
`

const CenteredSection = styled.section`
  min-height: 70vh;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
`;

const Header = styled.header`
  min-height: 90vh;
  display: flex;
  justify-content: center;
  align-items: center;
`

const GlobeSection = styled(CenteredSection)`
  width: 50%;
  text-align: center;
  margin: 0 auto;
`

const FoodsSection = styled(CenteredSection)`
  text-align: center;
`

const FavoriteSection = styled(CenteredSection)`
  flex-direction: row;
`;

const CookerSection = styled(CenteredSection)`
  margin: 0 auto;
`;
